apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-powerflex
  namespace: flux-system
spec:
  interval: 5m
  releaseName: csi-powerflex
  targetNamespace: powerflex
  chart:
    spec:
# TODO validate that path works
      chart: helm/csi-vxflexos
      version: '2.5.0'
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: csi-powerflex
        namespace: flux-system
      interval: 1m
# Original from :  https://github.com/dell/csi-powerflex/blob/v2.3.0/helm/csi-powerflex/values.yaml
  valuesFrom:
  - kind: ConfigMap
    name: csi-powerflex-helm-values
    valuesKey: values.yaml
