apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: csi-powerflex
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/dell/csi-powerflex/
  ref:
    tag: v2.5.0
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/helm/