# https://taskfile.dev

version: '3'

vars:
  NAME: infrastructure
  #  NAME: gitops-demo
  CLUSTER: eks 
  BRANCH: main
  USER: coulof
  NS: powerflex

tasks:
  flux:bootstrap:http:
    desc: bootstrap cluster with vanilla flux for infrastructure
    cmds:
      - |
        flux bootstrap github \
             --log-level debug \
             --owner=coulof \
             --repository=fluxcd-csm-powerflex \
             --branch={{ .CLUSTER }} \
             --path=clusters/{{ .CLUSTER }} \
             --personal

  flux:cleanup:flux:
    desc: remove flux
    cmds:
      - |
        flux uninstall -s --namespace=flux-system

  flux:cleanup:ns:
    desc: remove flux
    cmds:
      - kubectl delete all --all -n {{ .NS }}
      - kubectl delete ns {{ .NS }}
