---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dell
  namespace: flux-system

spec:
  interval: 30m
  url: https://dell.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csm-observability
  namespace: flux-system
spec:
  releaseName: csm-observability
  chart:
    spec:
      chart: karavi-observability
      sourceRef:
        kind: HelmRepository
        name: dell
        namespace: flux-system
      version: "1.3.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: csm-observability-values