apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csm-observability
  namespace: flux-system
spec:
  # TODO improve `targetNamespace` to be in `csm-lab` rather than here
  targetNamespace: powerflex
  releaseName: csm-observability
  chart:
    spec:
      chart: karavi-observability
      sourceRef:
        kind: HelmRepository
        name: dell
        namespace: flux-system
      version: "1.3.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: csm-observability-values