- username: "admin"
  password: "Password123"
  systemID: "1600b2cd7ac1c50f"
  endpoint: "https://172.31.44.243"
  skipCertificateValidation: true 
  mdm: "172.31.37.187,172.31.42.96"
  isDefault: true
