apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/csi-volumegroup-snapshotter
  - ../base/external-snapshotter
  - ../base/powerflex
  # - patchPowerFlexRelease.yaml
  - storageClass.yaml

generatorOptions:
  disableNameSuffixHash: true
# TODO https://fluxcd.io/flux/components/kustomize/kustomization/#kustomize-secretgenerator
secretGenerator:
  - name: csi-powerflex-config
    namespace: powerflex
    files:
    - config=config.yaml
    literals:
    - MDM=172.31.43.137,172.31.39.106

configMapGenerator:
  - name: csi-powerflex-helm-values
    namespace: flux-system
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml

patches:
  - target:
      group: source.toolkit.fluxcd.io
      version: v1beta2
      kind: GitRepository
      name: csi-powerflex
    patch: |-
      - op: replace
        path: /spec/url
        value: https://github.com/coulof/csi-powerflex/
      - op: replace
        path: /spec/ref
        value:
          branch: main