apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/powerflex/release.yaml
patches:
  - target:
      group: source.toolkit.fluxcd.io
      version: v1beta2
      kind: GitRepository
      name: csi-powerflex
    patch: |-
      - op: replace
        path: /spec/url
        value: https://github.com/coulof/csi-powerflex/