---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: powerflex
parameters:
  FsType: ext4
  storagepool: pool1
  systemID: 1600b2cd7ac1c50f
provisioner: csi-vxflexos.dellemc.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true