---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: dell-csi-volumegroup-snapshotter
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/dell/csi-volumegroup-snapshotter/
  ref:
    tag: v1.2.0
  ignore: |
    # exclude all
    /*
    # include charts directory
    !config/crd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dell-csi-volumegroup-snapshotter-crd
  namespace: flux-system
spec:
  interval: 10m
  # targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: dell-csi-volumegroup-snapshotter
  path: "./config/crd/"
  prune: true