apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cert-manager
  - ../base/csi-volumegroup-snapshotter
  - ../base/external-snapshotter
  - ../base/csm-observability
  - ../base/powerflex
  - storageClass.yaml

generatorOptions:
  disableNameSuffixHash: true
# TODO https://fluxcd.io/flux/components/kustomize/kustomization/#kustomize-secretgenerator
secretGenerator:
  - name: csi-powerflex-config
    namespace: powerflex
    files:
    - config=config.yaml
    literals:
    - MDM=10.157.10.32,10.158.10.32,10.159.10.32,10.160.10.32
  # TODO Improve
  - name: vxflexos-config
    namespace: powerflex
    files:
    - config=config.yaml
    literals:
    - MDM=10.157.10.32,10.158.10.32,10.159.10.32,10.160.10.32
  - name: karavi-authorization-config
    namespace: powerflex
    files:
    - config=karavi-authorization-config.json
  - name: proxy-server-root-certificate
    namespace: powerflex
    literals:
    - rootCertificate.pem=
configMapGenerator:
  - name: csi-powerflex-helm-values
    namespace: flux-system
    files:
      - values.yaml=values.yaml
  - name: csm-observability-values
    namespace: flux-system
    files:
      - values.yaml=csm-obs-values.yaml
configurations:
  - kustomizeconfig.yaml
