---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: powerflex
parameters:
  FsType: ext4
  storagepool: SP-1
  systemID: 394a9c0419757c0f
provisioner: csi-vxflexos.dellemc.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true