controller:
  healthMonitor:
    enabled: true
  volumeNamePrefix: csm
  controllerCount: 1

node:
  healthMonitor:
    enabled: true

vgsnapshotter:
  enabled: true
  image: dellemc/csi-volumegroup-snapshotter:v1.2.0

podmon:
  enabled: false
  image: dellemc/podmon:v1.3.0
  controller:
   args:
     - "--csisock=unix:/var/run/csi/csi.sock"
     - "--labelvalue=csi-vxflexos"
     - "--mode=controller"
     - "--skipArrayConnectionValidation=false"
     - "--driver-config-params=/vxflexos-config-params/driver-config-params.yaml"
     - "--driverPodLabelValue=dell-storage"
  node:
   args:
     - "--csisock=unix:/var/lib/kubelet/plugins/vxflexos.emc.dell.com/csi_sock"
     - "--labelvalue=csi-vxflexos"
     - "--mode=node"
     - "--leaderelection=false"
     - "--driver-config-params=/vxflexos-config-params/driver-config-params.yaml"
     - "--driverPodLabelValue=dell-storage"
